version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing Build Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Building Docs
          command: |
            . venv/bin/activate
            sphinx-build -b html -d build/doctrees source build/html

      - store_artifacts:
          path: build/html
          destination: docs

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/html s3://s3.us-east-2.amazonaws.com/dxl-docs/ --delete
            else
              echo "Not master branch so not deploying"
            fi
